// TODO: Convert to Enum after TypeScript integration.

export const AUTH_TYPE = {
  EXTENSION: 'extension',
  TWITTER: 'twitter',
  ETH: 'eth',
  USERNAME: 'username'
};

export const LOCAL_STORAGE_KEYS = {
  ETH_AUTH: 'YUP_ETH_AUTH',
  YUP_REWARDS: 'YUP_CLAIM_RWRDS',
  THEME_MODE: 'THEME_MODE',
  TWITTER_INFO: 'twitterMirrorInfo'
};

export const REACT_QUERY_KEYS = {
  YUP_LIST_FILTER: 'YUP_LIST_FILTER',
  YUP_LIST: 'YUP_LIST',
  YUP_COLLECTION: 'YUP_COLLECTION',
  YUP_RECOMMENDATION: 'YUP_RECOMMENDATION',
  YUP_INITIAL_VOTES: 'YUP_INITIAL_VOTES',
  YUP_SOCIAL_LEVEL: 'YUP_SOCIAL_LEVEL',
  FOLLOWING: 'FOLLOWING',
  FOLLOWER: 'FOLLOWER',
  USER_POSTS: 'USER_POSTS',
  USER_COLLECTIONS: 'USER_COLLECTIONS'
};

export const LOADER_TYPE = {
  DEFAULT: 'default'
};
